### ISSUE TITLE
Investigate why cUSD faucet transfers stopped

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/faucet#133]
From @ericnakagawa on [Slack](https://celo-org.slack.com/archives/C014SRL4URY/p1702181327509849): 
> Hi Arthur and team, we’re investigating some issues reported at the ETH Global Hackathon. The [cUSD wallet](https://celoscan.io/address/0x874069Fa1Eb16D44d622F2e0Ca25eeA172369bC1) distributions stopped 20 days back. CELO token was being distributed, but no mento Stables.

**Comment by 0xarthurxyz** [comment]
These two issues could benefit from being done in the same effort (to avoid future context switching):
- #90 
- https://github.com/celo-org/devrel-x-product-clabs/issues/2

(of course pending prioritisation, just linking here to not forget)
