### ISSUE TITLE
Further limit draining faucet before the hackathon weekend

### ISSUE THREAD

**Issue by ericnakagawa** [celo-org/faucet#164]
### Describe the feature you would like

I’d like a way to further limit draining of testnet faucet. 

One idea is to require GitHub auth via Social Connect to further limit abuse.

**Comment by arthurgousset** [comment]
Thanks for raising this @ericnakagawa 👍 

I checked, the faucet address ([0x22579CA45eE22E2E16dDF72D955D6cf4c767B0eF](https://alfajores.celoscan.io/address/0x22579ca45ee22e2e16ddf72d955d6cf4c767b0ef)) is indeed low on tokens. 

![image](https://github.com/celo-org/faucet/assets/46296830/934a790c-c250-42e3-b6c8-c1ec0db23ffd)

faucet.celo.org also display a message that the faucet is low on tokens:

![image](https://github.com/celo-org/faucet/assets/46296830/55db7642-0a56-4f00-a219-b700e6c41850)

**Comment by arthurgousset** [comment]
Eric is hosting a hackathon this weekend and needs the faucet to be accessible to devs.

**Comment by arthurgousset** [comment]
It looks like the current faucet balance is: 

1. cREAL: ~0.8
2. cUSD: ~1.2
3. cEUR: ~824,264
4. CELO: ~0.3

<img width="350" src="https://github.com/celo-org/faucet/assets/46296830/9e5f1390-0f75-4534-8ac1-30739df9c4ab">

Source: https://alfajores.celoscan.io/address/0x22579ca45ee22e2e16ddf72d955d6cf4c767b0ef

**Comment by arthurgousset** [comment]
Checking how much the faucet distributes at the moment.

From here 

https://github.com/celo-org/faucet/blob/c95522ef6f9f77a627d16ce0a769c2f8fbbe93cf/apps/firebase/src/database-helper.ts#L205-L222

we know it's the amounts set here

https://github.com/celo-org/faucet/blob/c95522ef6f9f77a627d16ce0a769c2f8fbbe93cf/apps/firebase/src/config.ts#L3-L12

Checking what the amounts are set to. 

Following the setup instructions in [readme.md](https://github.com/celo-org/faucet/blob/c95522ef6f9f77a627d16ce0a769c2f8fbbe93cf/readme.md#L69):

```sh
$ cd apps/firebase
$ yarn dlx firebase-tools@latest logim
# ...
$ yarn install
```

From [firebase/README.md](https://github.com/celo-org/faucet/blob/c95522ef6f9f77a627d16ce0a769c2f8fbbe93cf/apps/firebase/README.md#L33), we get the config values with:

```sh
$ yarn cli config:get --net alfajores
{
  // ...
  "authenticated_stable_amount": "5000000000000000000",
  "authenticated_gold_amount": "5000000000000000000",
  "faucet_gold_amount": "500000000000000000",
  "faucet_stable_amount": "500000000000000000",
  // ...
}
```

Converting from wei to ethers

```sh
# authenticated
$ cast from-wei 5000000000000000000 ether
5.000000000000000000

# not authenticated
$ cast from-wei 500000000000000000 ether
0.500000000000000000
```

**Comment by arthurgousset** [comment]
Ideas to avoid faucet being empty:
1. lower unauthenticated amount even more,

**Comment by arthurgousset** [comment]
Ideas to fill the faucet by the weekend: 
1. wait for validator rewards to come in
2. convert a portion of ~824,264 cEUR into CELO
3. Eric to fill faucet with tokens he has

**Comment by arthurgousset** [comment]
- [ ] Confirm that faucet is getting replenished

**Comment by arthurgousset** [comment]
The faucet is currently only getting replenished 

```sh
$ celocli network:parameters --node alfajores
... 
EpochRewards:
  carbonOffsetting:
    factor: 0.25
    partner: 0x22579CA45eE22E2E16dDF72D955D6cf4c767B0eF
...
```

**Comment by arthurgousset** [comment]
[Asked for help](https://clabsco.slack.com/archives/CJUGMBSSX/p1711713365953909) to make a short-term transfer to the faucet for the weekend hackathon.

**Comment by arthurgousset** [comment]
This address [`0x9803c7f37f26E3E4521f1d1B2a845Ae51e580aA0`](https://alfajores.celoscan.io/address/0xb8c3475d736ab7c587b3fcf6a4e2d55136d4968f#tokentxns) seems to be getting 5 `CELO` from the faucet repeatedly.

![image](https://github.com/celo-org/faucet/assets/46296830/60f72fc5-bda4-4df4-b386-317d574ac533)

Source:  https://alfajores.celoscan.io/address/0xb8c3475d736ab7c587b3fcf6a4e2d55136d4968f

It then seems to be sending them on to [`0x90C68A26B792814e99Ac8E337F5b1BB47136F9FF`](https://alfajores.celoscan.io/address/0x90c68a26b792814e99ac8e337f5b1bb47136f9ff)

![image](https://github.com/celo-org/faucet/assets/46296830/724cbe2d-d37a-4349-9d3a-345f507c4ab0)

Source: https://alfajores.celoscan.io/address/0xb8c3475d736ab7c587b3fcf6a4e2d55136d4968f

That address [`0x90C68A26B792814e99Ac8E337F5b1BB47136F9FF`](https://alfajores.celoscan.io/address/0x90c68a26b792814e99ac8e337f5b1bb47136f9ff) has a 11,190 `CELO` balance.

![image](https://github.com/celo-org/faucet/assets/46296830/79e2f640-20fd-4a00-bc63-9618291e1186)

Source: https://alfajores.celoscan.io/address/0x90c68a26b792814e99ac8e337f5b1bb47136f9ff

**Comment by arthurgousset** [comment]
The faucet balance has been drained by 100,000 `CELO` in 10 days. From Mar 19 to Mar 29, the balance dropped from 100,460 to near 0. 

![image](https://github.com/celo-org/faucet/assets/46296830/16676786-7af8-4258-9dd6-d16cbe817af6)

Source: https://explorer.celo.org/alfajores/address/0x22579CA45eE22E2E16dDF72D955D6cf4c767B0eF/coin-balances?block_number=23258880&items_count=50#address-tabs

**Comment by arthurgousset** [comment]
It might be necessary to limit the amount of `CELO` that can be sent out, whether the user is authenticated or not.

**Comment by arthurgousset** [comment]
The faucet seems to be funded by carbon offsetting rewards once per epoch (= day): 

![Uploading image.png…]()

![image](https://github.com/celo-org/faucet/assets/46296830/0cb229f8-8ec8-400c-b4f5-ee5fd3fb961d)

Source: https://explorer.celo.org/alfajores/block/23241600/epoch-transactions

**Comment by arthurgousset** [comment]
The funding amount fluctuates with use, because carbon offset rewards depend on network usage. In recent days it's around ~900-1,000 `CELO` per day, but not sure what it looks like before:

![image](https://github.com/celo-org/faucet/assets/46296830/4786eb1b-57d7-438a-9f13-8164dda4d16c)

Source: https://explorer.celo.org/alfajores/block/23241600/epoch-transactions

![image](https://github.com/celo-org/faucet/assets/46296830/f5ebf76f-2f1f-4fa2-ac52-3b2d4d042dab)

Source: https://explorer.celo.org/alfajores/block/23224320/epoch-transactions

![image](https://github.com/celo-org/faucet/assets/46296830/bfd9f698-d66b-4fe6-b243-3decd279259b)

Source: https://explorer.celo.org/alfajores/block/23207040/epoch-transactions

**Comment by arthurgousset** [comment]
Other ideas to limit abuse:
1. Adjust the amount that is sent based on the recipient's balance (if CELO balance high, send less)
2. Check reCaptcha is required when user is Github authenticated (seems like a bot is making 5 `CELO` requests repeatedly)

**Comment by arthurgousset** [comment]
The faucet used be funded every hour: 
- https://github.com/celo-org/faucet/pull/47

**Comment by arthurgousset** [comment]
This address [0xb8c3475d736ab7c587b3fcf6a4e2d55136d4968f](https://explorer.celo.org/alfajores/address/0xb8c3475d736ab7c587b3fcf6a4e2d55136d4968f) seems to be running an automated process. 

Eric briefly funded the faucet with 25 `CELO` and the address above automatically started making 5 `CELO` requests until the faucet was empty: 

![image](https://github.com/celo-org/faucet/assets/46296830/aaa2d10a-1988-4f76-afb0-e3e94462b535)

Source: https://explorer.celo.org/alfajores/address/0x22579CA45eE22E2E16dDF72D955D6cf4c767B0eF

**Comment by jcortejoso** [comment]
Hi @arthurgousset ! Thanks for the explanation.

Do we know what authentication method is the draining bot using?

**Comment by arthurgousset** [comment]
This address [`0xbabe97E806Ae3a153A94F2ee564cD8cCeA1Dc913`](https://explorer.celo.org/alfajores/address/0xbabe97E806Ae3a153A94F2ee564cD8cCeA1Dc913/transactions#address-tabs) is also "attacking" the faucet and sending to the same address as above

**Comment by arthurgousset** [comment]
> Hi @arthurgousset ! Thanks for the explanation.
> 
> Do we know what authentication method is the draining bot using?

Yes, the bot is using a Github authenticated account to request 5 `CELO` instead of `0.5` for unauthenticated accounts.

But, more importantly, we have a mechanism in place that doesn't fund any address that has more than 20 `CELO`. But, there was a bug that prevented that from working. 
It's fixed here: 
- https://github.com/celo-org/faucet/pull/167

**Comment by arthurgousset** [comment]
Whenever the bot's balance is above 20, the faucet doesn't send tokens as expected 👍 

Here [0xbabe97E806Ae3a153A94F2ee564cD8cCeA1Dc913](https://explorer.celo.org/alfajores/address/0xbabe97E806Ae3a153A94F2ee564cD8cCeA1Dc913/transactions#address-tabs) has 21.25 `CELO`. So requests stop until the bot sends `CELO` away and the balance drops below 20.

![image](https://github.com/celo-org/faucet/assets/46296830/de2d7839-8da8-485e-b710-59bd5107e628)

Source: https://explorer.celo.org/alfajores/address/0xbabe97E806Ae3a153A94F2ee564cD8cCeA1Dc913/coin-balances#address-tabs

**Comment by arthurgousset** [comment]
[`0xbabe97E806Ae3a153A94F2ee564cD8cCeA1Dc913`](https://explorer.celo.org/alfajores/address/0xbabe97E806Ae3a153A94F2ee564cD8cCeA1Dc913/transactions#address-tabs) is sending tokens to [`0x6FF76397c1d9aAFD63DFdB63C0C701d061d3d822`](https://explorer.celo.org/alfajores/address/0x6FF76397c1d9aAFD63DFdB63C0C701d061d3d822/transactions#address-tabs), which currently has a balance of 10,828 `CELO`

![image](https://github.com/celo-org/faucet/assets/46296830/3a349298-433b-49db-975d-fe5a23bb36bf)

Source: https://explorer.celo.org/alfajores/address/0x6FF76397c1d9aAFD63DFdB63C0C701d061d3d822/transactions#address-tabs

![image](https://github.com/celo-org/faucet/assets/46296830/a8e8cced-7cc4-45d3-8d45-5966bdbf5fd3)

Source: https://explorer.celo.org/alfajores/address/0x6FF76397c1d9aAFD63DFdB63C0C701d061d3d822/token-transfers#address-tabs

**Comment by arthurgousset** [comment]
(for future reference)
Javi topped the faucet up with [50,000 CELO](https://alfajores.celoscan.io/tx/0x63482956c30bac3ba8f3086713f878bc94e0424991b161cd6235d72bd369dd04)

**Comment by arthurgousset** [comment]
We also sent @ericnakagawa [50,000 CELO](https://alfajores.celoscan.io/tx/0x472e2fdad0b4b4c777103486b8f28a89e0171c6e69bee1ff75a4dba960ff13bf) as a short-term fix for the weekend. That way he can top up the faucet independently, if he has a short-term need, and the faucet is still affected by the abuse.

**Comment by arthurgousset** [comment]
I'm closing this issue as it pertains to the hackathon weekend. 

I'll open a new issue and PR for longer-term changes to prevent abuse.
