### ISSUE TITLE
Remove access to Stablecoin and add Guide to the Mento page

### ISSUE THREAD

**Issue by GigaHierz** [celo-org/faucet#197]
## Current Status

Currently, cUSD needs to be constantly refilled for the faucet, which is hard to maintain as it's not automated. 
Additionally, the whole UX is not clear on where and when to receive the tokens. This is a temporary fix, as it is technically still possible to claim the tokens, but the work to remove this from the firebase is a bigger project, and providing the access rights for testing might be too difficult to coordinate. 

## Proposed Solution

- [ ] remove the "Celo only" check box, 
- [ ] set "skipStables" to ALWAYS "true"
- [ ] Add the info to the "Add Celo Testnet" button, that mento tokens will be added as well. "Add Mento Stablecoins to your Wallet"
- [ ] Instead of "Faucet" the button should say "Claim CELO"
- [ ] Add info to get Celo stables like cUSD, sREAL, cEUR, cKES, PUSO and more on [mento](https://app.mento.org/). "To get stablecoins on Celo, check out Mento Exchange where you can exchange your CELO tokens for cUSD. If you need any other stablecoin like USDC, USDT, PUSO, cKES, cCOP you can now exchange them for cUSD. "

## Future implementation
- [ ] optionally create a ticket for their frontend for Alfajores and reach out to their team to add that to the Scout Game. 
- [ ] remove the option to claim Mento Stable tokens from the firebase

**Comment by Ronexlemon** [comment]
hello @nicolasbrugneaux  can i be assigned this issue
