### ISSUE TITLE
Add faucet.celo.org to main celo.org website

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/faucet#31]

**Comment by aaronmgdr** [comment]
I asked the team in charge of the celo website to update al links to celo.org/developers/faucet to faucet.celo.org

and to create redirect

**Comment by aaronmgdr** [comment]
I have asked dev rel to update faucet links on the docs website

**Comment by aaronmgdr** [comment]
all links on docs.celo.org have been updated

**Comment by aaronmgdr** [comment]
redirect  from old developers/faucet to faucet.celo.org  is now in place

**Comment by aaronmgdr** [comment]
foundation web team said it would be a few weeks to change the links there. Since there is a redirect now id say actually changing those is low priority so Im going to mark this as closed

**Comment by 0xarthurxyz** [comment]
Thanks for the comments in here!

**Comment by aaronmgdr** [comment]
just got word they ended up completing all links!

**Comment by 0xarthurxyz** [comment]
The font renders white for me (Chrome browser, 11.23pm)
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/46296830/216473496-ee47d2cf-eeef-4a64-b9f5-a0d7f0c47569.png">

**Comment by 0xarthurxyz** [comment]
- [ ] Nit (if possible): Icon in browser is Vercel logo. Any chance we can change that Celo icon?

<img width="241" alt="image" src="https://user-images.githubusercontent.com/46296830/216473879-99e49efe-24c8-4106-a870-13da78ce072d.png">

**Comment by aaronmgdr** [comment]
https://github.com/celo-org/faucet/pull/32

**Comment by 0xarthurxyz** [comment]
(for visibility) Change URL to faucet.celo.org in celo-org/[faucet](https://github.com/celo-org/faucet)

<img width="334" alt="image" src="https://user-images.githubusercontent.com/46296830/216474228-8f518799-caaf-4538-b594-c181c2a341a5.png">

**Comment by aaronmgdr** [comment]
https://faucet-git-aaronmgdr-fix-foreground-color-c-labs.vercel.app/

**Comment by 0xarthurxyz** [comment]
- [ ] Nit: Address box is blue upon clicking. Is this expected behaviour? 

<img width="548" alt="image" src="https://user-images.githubusercontent.com/46296830/216602858-d38573c6-72de-40e9-ae63-1a8581912b28.png">

**Comment by 0xarthurxyz** [comment]
- [ ] Nit: Account Address is serif font (doesn't render in same font as text above)

<img width="443" alt="image" src="https://user-images.githubusercontent.com/46296830/216602982-a0afaed6-e156-4a4c-a15b-ebe06a968a08.png">

**Comment by 0xarthurxyz** [comment]
- [ ] Nit: Could we replace the text above the address box with the following:

> Enter your testnet address below. Each request gives you:
> - 5 CELO
> - 5 cUSD
> - 5 cEUR
> - 5 cREAL

**Comment by aaronmgdr** [comment]
> * [ ]  Nit: Address box is blue upon clicking. Is this expected behaviour?
> 
> <img alt="image" width="548" src="https://user-images.githubusercontent.com/46296830/216602858-d38573c6-72de-40e9-ae63-1a8581912b28.png">

that is standard behavior yes.  elements should always have s glow when active/focused for accessibility.
