### ISSUE TITLE
Investigate improved protection for faucet

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/faucet#46]
Proposal in this Google doc: [[1p] Protected Faucet MVP](https://docs.google.com/document/d/1bfP6WAQuzh1KXlF4OGOzKsqHnJi6JufYuH0khylbZCc/edit#)

Definition of done: 

- this is done when we can make code changes to the faucet to prevent it being drained

**Comment by 0xarthurxyz** [comment]
Sprint planning: 

- [ ] someone else takes a look at the proposal @dckesler and @0xarthurxyz

**Comment by 0xarthurxyz** [comment]
Proposal in this Google doc: [[1p] Authenticated Faucet ](https://docs.google.com/document/d/1bfP6WAQuzh1KXlF4OGOzKsqHnJi6JufYuH0khylbZCc/edit#)
