### ISSUE TITLE
Consider borrowing UI idea from faucet.quicknode.com to encourage users to get more tokens

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/faucet#61]
[Quicknode's multifaucet](https://faucet.quicknode.com/drip) has a nice UI that lets you:
- share a tweet to get more tokens (we could replace this with "authenticate with Github to get more tokens"

![Image](https://user-images.githubusercontent.com/46296830/229575801-a48e10de-dcfc-40e7-a42f-7c377c5d2758.png)

**Comment by aaronmgdr** [comment]
i think this was implemented
